# NumPy Arrays

In [1]:
import numpy as np

## Vector (1-D)

In [2]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

## Matrics

In [3]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Remember number of brackets show the dimension
#### [ ] vector
#### [[ ]] matrix 2-D

## Generation Methods

In [8]:
arr1 = np.arange(0,10)
arr2 = np.arange(0,10,2)

print(arr1)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [12]:
arr1 = np.zeros(3) #1-d
arr2 = np.zeros((2,3)) #2-d (rows,columns)

print(arr1)
print(arr2)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,5,10) 

# Third element is number of points
# Points are evenly spaced

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
# Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
arr1 = np.random.rand(5)
# 1d array, from 0 to 1

arr2 = np.random.rand(5,4) 
# 2d metrix

print(arr1)
print(arr2)

[0.87805939 0.99338774 0.11863572 0.19597276 0.90191351]
[[0.37968964 0.65026695 0.11013683 0.46046623]
 [0.45988195 0.42531513 0.49430237 0.35066566]
 [0.50311051 0.68036316 0.04847795 0.35944671]
 [0.18279817 0.95941742 0.09018049 0.22420541]
 [0.41643271 0.3473851  0.26848591 0.08583119]]


In [21]:
np.random.randn(2)
# 2 random numbers from a standard normal distribution
np.random.randn(4,4)

array([[ 0.59622262,  1.93462993, -1.36894541,  0.60400896],
       [ 0.07048571,  0.23423048,  0.23633338,  0.31133551],
       [ 0.10727505, -1.84340962, -0.91726852, -0.9214301 ],
       [-0.83865152,  0.7104734 ,  0.51951223,  0.62287706]])

In [24]:
np.random.randint(1,100)
# 1 <=random integer < 100

np.random.randint(1,100,10) 
# 10 is the number of points

array([98, 59, 14, 92, 41, 64, 79, 24, 85, 26])

In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 7 41 27  2 35 43 30  7 43 20]


In [27]:
arr.reshape(5,5)

#Number of elements should fit into the size of matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
# Max and Min
print(ranarr.max())
print(ranarr.min())

43
2


In [29]:
# Index of Max and Min in the array
print(ranarr.argmax())
print(ranarr.argmin())

5
3


In [30]:
arr = arr.reshape(5,5)
arr.shape
# showing number of rows and columns

(5, 5)

# Indexing

## Vectors

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Indexing is like python lists
arr[8]

8

In [5]:
# Slicing
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Broadcasting

In [10]:
slice_of_arr = arr[0:6]
slice_of_arr[:] = 99
slice_of_arr


array([99, 99, 99, 99, 99, 99])

In [11]:
# with above changes the main arr will be changed too
# Slice_of_arr is just a view of data not a copy of them
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
# Getting a copy
arr_copy = arr.copy()
arr_copy[:] = 100

arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [13]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## 2D array (matrices)

In [15]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

##### Format is arr_2d[row][col] or arr_2d[row,col]

In [16]:
# Single bracket notation is preferable
arr_2d[2,1]

40

In [17]:
# 2D array slicing
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [20]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
# length of array
arr_length = arr2d.shape[1]
arr_length

10

In [26]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [27]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

## Selection

In [28]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [30]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])